kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker compose down
      - docker compose up -d --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
